// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1705235961);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1705282045);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1705278321);
user_pref("app.update.lastUpdateTime.region-update-timer", 1705149560);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1705278321);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1705235961);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1705213543);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1705235961);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{9c32170d-feed-4f40-bc79-ca08b8fb8ffc}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1705149531);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 137);
user_pref("browser.newtabpage.activity-stream.impressionId", "{d92c3f70-b4fc-42ad-b825-449085d3b5fa}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20230807082803");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20230807082803");
user_pref("browser.startup.homepage_override.mstone", "116.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1705213486);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1705149535220");
user_pref("devtools.debugger.prefs-schema-version", 11);
user_pref("devtools.everOpened", true);
user_pref("devtools.netmonitor.msg.visibleColumns", "[\"data\",\"time\"]");
user_pref("devtools.performance.recording.entries", 134217728);
user_pref("devtools.performance.recording.features", "[\"screenshots\",\"js\",\"cpu\"]");
user_pref("devtools.performance.recording.threads", "[\"GeckoMain\",\"Compositor\",\"Renderer\",\"DOM Worker\"]");
user_pref("devtools.toolbox.selectedTool", "storage");
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 700);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 350);
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "116.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1705235961);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-US@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20230807082803");
user_pref("extensions.lastAppVersion", "116.0.2");
user_pref("extensions.lastPlatformVersion", "116.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"64cc3383-499a-4980-b254-0fc5fb798107\",\"pictureinpicture@mozilla.org\":\"6eea3644-4c4a-447c-8db1-6c1455dfc9e1\",\"screenshots@mozilla.org\":\"5e0ce6f2-7752-465b-908c-334b44c7994b\",\"webcompat-reporter@mozilla.org\":\"f11464ec-b2be-4114-a666-38ccd798f7c0\",\"webcompat@mozilla.org\":\"c67b41aa-49ce-4699-81bd-7b677af548f3\",\"default-theme@mozilla.org\":\"61846f71-5f38-4e8a-b69b-d38e0e4fc9c2\",\"addons-search-detection@mozilla.com\":\"97c39ac9-3a26-4d69-8eea-f1dd8bf3c079\",\"google@search.mozilla.org\":\"0861c8dc-aeb8-4d5e-9702-8f515702f0af\",\"amazondotcom@search.mozilla.org\":\"c50294ac-2b1d-4a7e-97c8-66788210b97a\",\"wikipedia@search.mozilla.org\":\"7229443d-4677-43e0-a1f9-a97fc5809566\",\"bing@search.mozilla.org\":\"e8b211a0-7b47-4998-8796-bcfa0836d127\",\"ddg@search.mozilla.org\":\"5fe2d095-3911-4bd8-b471-5df1c1c4c551\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1705213787);
user_pref("media.gmp-gmpopenh264.lastDownloadFailReason", "Error: Failed downloading via ServiceRequest, status: 0, channelStatus: 2152398878, errorCode: 2, reason: error");
user_pref("media.gmp-gmpopenh264.lastDownloadFailed", 1705213559);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1705213559);
user_pref("media.gmp-manager.buildID", "20230807082803");
user_pref("media.gmp-manager.lastCheck", 1705213559);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1705213787);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1705213787507");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "f0a0fa77-ae63-40ac-be16-d177182eb1a0");
user_pref("services.sync.engine.addresses.available", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1705213787);
user_pref("toolkit.startup.last_success", 1705213482);
user_pref("toolkit.telemetry.cachedClientID", "9339b24a-21cb-4fa8-97d7-19ed036596d7");
user_pref("toolkit.telemetry.previousBuildID", "20230807082803");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
